const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Tilemap,
		C3.Plugins.Arr,
		C3.Plugins.NinePatch,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Tilemap.Exps.X,
		C3.Plugins.Tilemap.Exps.TileWidth,
		C3.Plugins.Tilemap.Exps.Y,
		C3.Plugins.Tilemap.Exps.TileHeight,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Exps.IID,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Acts.SetLayerAngle,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Browser.Acts.Close,
		C3.Behaviors.Fade.Acts.StartFade
	];
};
self.C3_JsPropNameTable = [
	{dir: 0},
	{state: 0},
	{speed: 0},
	{nextDir: 0},
	{preferredDir: 0},
	{alternateDir: 0},
	{lastDir: 0},
	{frightened: 0},
	{eaten: 0},
	{frightenedTimer: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{Blinky: 0},
	{houseTimer: 0},
	{targetY: 0},
	{scatterX: 0},
	{scatterY: 0},
	{Clyde: 0},
	{Inky: 0},
	{isTeleport: 0},
	{score: 0},
	{powerActive: 0},
	{powerTimer: 0},
	{snapX: 0},
	{snapY: 0},
	{Bullet: 0},
	{Pacs: 0},
	{Pacz: 0},
	{Pinky: 0},
	{ButtonContinuePause: 0},
	{ButtonDown: 0},
	{ButtonLeft: 0},
	{ButtonMenuPause: 0},
	{ButtonPause: 0},
	{ButtonRight: 0},
	{ButtonUp: 0},
	{PauseOverlay: 0},
	{PauseText: 0},
	{Fade: 0},
	{Flashing: 0},
	{GhostHouseDoor: 0},
	{LivesText: 0},
	{isUsed: 0},
	{PathMarker: 0},
	{isDangerous: 0},
	{Pellet: 0},
	{PelletMarker: 0},
	{currentEffect: 0},
	{PowerPellet: 0},
	{ScoreText: 0},
	{Strawberry: 0},
	{TimerText: 0},
	{TitleText: 0},
	{TunnelLeft: 0},
	{TunnelRight: 0},
	{Wall: 0},
	{EffectLogText: 0},
	{Cherry: 0},
	{WallTeleport: 0},
	{Dark: 0},
	{Apple: 0},
	{Continue: 0},
	{DialogueArray: 0},
	{DialogueText: 0},
	{NameText: 0},
	{TextBox: 0},
	{ButtonLevel1: 0},
	{ButtonLevel2: 0},
	{ButtonLevel3: 0},
	{ButtonLevel4: 0},
	{ButtonLevel5: 0},
	{ButtonLevel6: 0},
	{ButtonLevel7: 0},
	{ButtonLevel8: 0},
	{ButtonLevel9: 0},
	{Level1LivesText: 0},
	{Level1TimeText: 0},
	{Level2LivesText: 0},
	{Level2TimeText: 0},
	{Level3LivesText: 0},
	{Level3TimeText: 0},
	{Level4LivesText: 0},
	{Level4TimeText: 0},
	{Level5LivesText: 0},
	{Level5TimeText: 0},
	{Level6LivesText: 0},
	{Level6TimeText: 0},
	{Level7LivesText: 0},
	{Level7TimeText: 0},
	{Level8LivesText: 0},
	{Level8TimeText: 0},
	{Level9LivesText: 0},
	{Level9TimeText: 0},
	{ButtonCredits: 0},
	{ButtonExit: 0},
	{ButtonLevels: 0},
	{ButtonMenuCredits: 0},
	{ButtonNewGame: 0},
	{CreditsBG: 0},
	{MenuText: 0},
	{BG: 0},
	{Keyboard: 0},
	{Audio: 0},
	{Touch: 0},
	{Browser: 0},
	{Text: 0},
	{LocalStorage: 0},
	{gameEnding: 0},
	{isDying: 0},
	{pelletsEaten: 0},
	{eatenPelletsPositions: 0},
	{totalScore: 0},
	{playerLives: 0},
	{gameOver: 0},
	{levelTime: 0},
	{levelStarted: 0},
	{isPaused: 0},
	{levelStartTimer: 0},
	{corruptedPPTimer: 0},
	{corruptedPPActive: 0},
	{strawberryTimer: 0},
	{strawberrySpawnDelay: 0},
	{strawberryLifetime: 0},
	{strawberryActive: 0},
	{strawberryEffectTimer: 0},
	{strawberryActiveEffect: 0},
	{pelletsEaten4: 0},
	{eatenPelletsPositions4: 0},
	{wallTeleportTimer: 0},
	{wallTeleportInterval: 0},
	{wallTeleportCount: 0},
	{cherryTimer: 0},
	{cherrySpawnDelay: 0},
	{cherryLifetime: 0},
	{cherryActive: 0},
	{dangerousPelletTimer: 0},
	{dangerousPelletCount: 0},
	{inkyFleeing: 0},
	{blackoutActive: 0},
	{blackoutTimer: 0},
	{blackoutDelay: 0},
	{flipTimer: 0},
	{flipInterval: 0},
	{isFlipped: 0},
	{dialogueIndex: 0},
	{isTyping: 0},
	{currentCharIndex: 0},
	{typingSpeed: 0},
	{typingTimer: 0},
	{fullDialogue: 0},
	{dialogueIndex5: 0},
	{isTyping5: 0},
	{currentCharIndex5: 0},
	{typingSpeed5: 0},
	{typingTimer5: 0},
	{fullDialogue5: 0},
	{intermezzoState: 0},
	{intermezzoTimer: 0},
	{level1Retries: 0},
	{level2Retries: 0},
	{level3Retries: 0},
	{level4Retries: 0},
	{level5Retries: 0},
	{level6Retries: 0},
	{level7Retries: 0},
	{level8Retries: 0},
	{level9Retries: 0},
	{level1Time: 0},
	{level2Time: 0},
	{level3Time: 0},
	{level4Time: 0},
	{level5Time: 0},
	{level6Time: 0},
	{level7Time: 0},
	{level8Time: 0},
	{level9Time: 0},
	{currentLevel: 0},
	{eatenPowerPelletsPositions: 0},
	{appleVisible: 0}
];

self.InstanceType = {
	Blinky: class extends self.ISpriteInstance {},
	Clyde: class extends self.ISpriteInstance {},
	Inky: class extends self.ISpriteInstance {},
	Pacs: class extends self.ISpriteInstance {},
	Pacz: class extends self.ISpriteInstance {},
	Pinky: class extends self.ISpriteInstance {},
	ButtonContinuePause: class extends self.ISpriteInstance {},
	ButtonDown: class extends self.ISpriteInstance {},
	ButtonLeft: class extends self.ISpriteInstance {},
	ButtonMenuPause: class extends self.ISpriteInstance {},
	ButtonPause: class extends self.ISpriteInstance {},
	ButtonRight: class extends self.ISpriteInstance {},
	ButtonUp: class extends self.ISpriteInstance {},
	PauseOverlay: class extends self.ISpriteInstance {},
	PauseText: class extends self.ITextInstance {},
	Flashing: class extends self.ISpriteInstance {},
	GhostHouseDoor: class extends self.ISpriteInstance {},
	LivesText: class extends self.ITextInstance {},
	PathMarker: class extends self.ISpriteInstance {},
	Pellet: class extends self.ISpriteInstance {},
	PelletMarker: class extends self.ISpriteInstance {},
	PowerPellet: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	Strawberry: class extends self.ISpriteInstance {},
	TimerText: class extends self.ITextInstance {},
	TitleText: class extends self.ITextInstance {},
	TunnelLeft: class extends self.ISpriteInstance {},
	TunnelRight: class extends self.ISpriteInstance {},
	Wall: class extends self.ITilemapInstance {},
	EffectLogText: class extends self.ITextInstance {},
	Cherry: class extends self.ISpriteInstance {},
	WallTeleport: class extends self.ISpriteInstance {},
	Dark: class extends self.ISpriteInstance {},
	Apple: class extends self.ISpriteInstance {},
	Continue: class extends self.ISpriteInstance {},
	DialogueArray: class extends self.IArrayInstance {},
	DialogueText: class extends self.ITextInstance {},
	NameText: class extends self.ITextInstance {},
	TextBox: class extends self.I9PatchInstance {},
	ButtonLevel1: class extends self.ISpriteInstance {},
	ButtonLevel2: class extends self.ISpriteInstance {},
	ButtonLevel3: class extends self.ISpriteInstance {},
	ButtonLevel4: class extends self.ISpriteInstance {},
	ButtonLevel5: class extends self.ISpriteInstance {},
	ButtonLevel6: class extends self.ISpriteInstance {},
	ButtonLevel7: class extends self.ISpriteInstance {},
	ButtonLevel8: class extends self.ISpriteInstance {},
	ButtonLevel9: class extends self.ISpriteInstance {},
	Level1LivesText: class extends self.ITextInstance {},
	Level1TimeText: class extends self.ITextInstance {},
	Level2LivesText: class extends self.ITextInstance {},
	Level2TimeText: class extends self.ITextInstance {},
	Level3LivesText: class extends self.ITextInstance {},
	Level3TimeText: class extends self.ITextInstance {},
	Level4LivesText: class extends self.ITextInstance {},
	Level4TimeText: class extends self.ITextInstance {},
	Level5LivesText: class extends self.ITextInstance {},
	Level5TimeText: class extends self.ITextInstance {},
	Level6LivesText: class extends self.ITextInstance {},
	Level6TimeText: class extends self.ITextInstance {},
	Level7LivesText: class extends self.ITextInstance {},
	Level7TimeText: class extends self.ITextInstance {},
	Level8LivesText: class extends self.ITextInstance {},
	Level8TimeText: class extends self.ITextInstance {},
	Level9LivesText: class extends self.ITextInstance {},
	Level9TimeText: class extends self.ITextInstance {},
	ButtonCredits: class extends self.ISpriteInstance {},
	ButtonExit: class extends self.ISpriteInstance {},
	ButtonLevels: class extends self.ISpriteInstance {},
	ButtonMenuCredits: class extends self.ISpriteInstance {},
	ButtonNewGame: class extends self.ISpriteInstance {},
	CreditsBG: class extends self.ISpriteInstance {},
	MenuText: class extends self.ITextInstance {},
	BG: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {}
}